### ISSUE TITLE
gray spectrograms vs colored spectrograms

### ISSUE THREAD

**Issue by hannraoi** [despoisj/DeepAudioClassification#11]
Hi~
Really appreciate your implementation ! It worked very well on my machine.
I have read your code and I found that the spectrograms is in gray format, and could you explain that why you chose gray  spectrograms instead of colored ones? Does gray images have better results than colored images?
Thanks a lot.

**Comment by despoisj** [comment]
I believe that the color palette used in spectrograms doesn't matter. It
encodes the intensity of the frequency at a given time. The advantage of
using grayscale is that the Convolutional Neural Network sees as input an
image of Height x Width x 1 instead of Height x Width x 3 for RGB images
(one color for each channel).


Hope that helps :)

2017-08-03 11:12 GMT+02:00 hannraoi <notifications@github.com>:

**Comment by hannraoi** [comment]
I think you are right. Thank u so much :)
